name : Deploy to Staging

on:
  push:
    branches:
        - develop

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Deploy Docker
          run : curl ${{secrets.RENDER_DEPLOY_HOOK_DEVELOP}}
